import lvgl as lv

class SYMBOL:
    CLOCK = ''
    RELOAD = ''
    SUN = ''
    MOON = ''
    MAN = ''
    WOMAN = ''
    ACCESSIBILITY = ''
    BELL_DISABLE = ''
    TEMP_HIGH = ''
    TEMP_LOW = ''
    HEART_RATE = ''
    HEART = ''
    CALCULATOR = ''
    CALENDAR = '' # calendar
    WALK = '' # walk
    USER_CONFIG = '' # user_cofig
    SHOE_PRINT = '' # shoe print
    WEIGHT = '' # weight
    RAIN = '' # rain
    HEAVY_RAIN = '' # heavy rain
    SNOW = ''
    WIND = '' # wind
    SMOG = '' # smog
    CLOUD = ''
    HOURGLASS = ''
    GPS = '' #GPS
    PHONE = ''
    CHIP = ''
    CLOUD_BOLT = '' # cloud bolt
    TORNADO = '🌪'
    STOPWATCH = '⏱'
    COMMENT = '' # comment
    TOGGLE_OFF = ''
    TOGGLE_ON = ''
    DISC = '💿'
    DICE_1 = '⚀'
    DICE_2 = '⚁'
    DICE_3 = '⚂'
    DICE_4 = '⚃'
    DICE_5 = '⚄'
    DICE_6 = '⚅'